# Generated by Django 4.2.3 on 2023-08-21 14:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Handshake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('is_succeed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Moonshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('is_succeed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=10)),
                ('year', models.PositiveSmallIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(2023), django.core.validators.MaxValueValidator(2100)])),
                ('status', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved')], default='created', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goal_created_by', to=settings.AUTH_USER_MODEL)),
                ('handshakes', models.ManyToManyField(to='goal.handshake')),
                ('moonshots', models.ManyToManyField(to='goal.moonshot')),
                ('target_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goal_target_employee', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goal_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_access_all_goal', 'can access all goal'),),
            },
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.UniqueConstraint(fields=('year', 'quarter', 'target_employee'), name='unique_oit_year_quarter'),
        ),
    ]
