# Generated by Django 4.2.3 on 2023-08-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='goal',
            name='unique_oit_year_quarter',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='year',
            new_name='assignment_year',
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.UniqueConstraint(fields=('assignment_year', 'quarter', 'target_employee'), name='unique_oit_year_quarter'),
        ),
    ]
