# Generated by Django 4.2.3 on 2023-08-21 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueassessment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='value',
            name='unique_role_year',
        ),
        migrations.RemoveField(
            model_name='value',
            name='assignment_date',
        ),
        migrations.RemoveField(
            model_name='valueassessment',
            name='assignment_date',
        ),
        migrations.AddField(
            model_name='value',
            name='year',
            field=models.PositiveSmallIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(2023), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddConstraint(
            model_name='value',
            constraint=models.UniqueConstraint(fields=('year', 'role'), name='unique_role_year'),
        ),
    ]
