# Generated by Django 4.2.3 on 2023-08-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueassessment', '0002_remove_value_unique_role_year_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='value',
            name='unique_role_year',
        ),
        migrations.RenameField(
            model_name='value',
            old_name='year',
            new_name='assignment_year',
        ),
        migrations.AddConstraint(
            model_name='value',
            constraint=models.UniqueConstraint(fields=('assignment_year', 'role'), name='unique_role_year'),
        ),
    ]
