FROM python:3.9-slim-buster

ENV PYTHONUNBUFFERED=1

RUN pip install pipenv

ENV PATH="$VIRTUAL_ENV/bin:$PATH"

WORKDIR /code
COPY . /code
RUN apt update && \
	apt install libpq-dev python3-dev g++ unixodbc-dev gnupg2 curl gettext fonts-freefont-ttf -y && \
    pipenv install --system --deploy

EXPOSE 8000

ENTRYPOINT ["bash", "./entrypoint.sh"]
